codecov:
  token: 60a8d8f2-fa0c-4bd5-8631-539c4e6bcf37

coverage:
  status:
    changes: off
    patch: off
    project:
      default:
        # coverage can drop up to 5% for the whole project before failing the commit
        threshold: 5
